using Microsoft.Pex.Framework.Generated;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using LinqToWiki.Collections;
// <copyright file="DictionaryDictionaryTKey1TKey2TValueTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Collections.Tests
{
    public partial class DictionaryDictionaryTKey1TKey2TValueTest
    {

[TestMethod]
[PexGeneratedBy(typeof(DictionaryDictionaryTKey1TKey2TValueTest))]
public void Constructor174()
{
    DictionaryDictionary<int, int, int> dictionaryDictionary;
    dictionaryDictionary = this.Constructor<int, int, int>();
    Assert.IsNotNull((object)dictionaryDictionary);
    Assert.IsNotNull
        (((Dictionary<int, Dictionary<int, int>>)dictionaryDictionary).Comparer);
    Assert.AreEqual<int>
        (0, ((Dictionary<int, Dictionary<int, int>>)dictionaryDictionary).Count);
}
    }
}
