using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using LinqToWiki.Internals;
using LinqToWiki.Download;
// <copyright file="DownloaderTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Download.Tests
{
    public partial class DownloaderTest
    {

[TestMethod]
[PexGeneratedBy(typeof(DownloaderTest))]
public void Constructor836()
{
    Downloader downloader;
    downloader = this.Constructor((WikiInfo)null);
    Assert.IsNotNull((object)downloader);
}
    }
}
