using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using LinqToWiki;
using System.Xml.Linq;
using LinqToWiki.Download;
using LinqToWiki.Internals;
// <copyright file="DownloaderTest.Download.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Download.Tests
{
    public partial class DownloaderTest
    {

[TestMethod]
[PexGeneratedBy(typeof(DownloaderTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException159()
{
    WikiInfo wikiInfo;
    Downloader downloader;
    XDocument xDocument;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("", "@1#\"", (string)null, (IEnumerable<Namespace>)namespaces);
    downloader = DownloaderFactory.Create(wikiInfo);
    xDocument = this.Download(downloader, (IEnumerable<HttpQueryParameterBase>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(DownloaderTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException15901()
{
    object o;
    WikiInfo wikiInfo;
    Downloader downloader;
    XDocument xDocument;
    o = NamespaceFactory.Create(0);
    Namespace[] namespaces = new Namespace[1];
    namespaces[0] = (Namespace)o;
    wikiInfo = WikiInfoFactory.Create
                   ("", "@1#\"", (string)null, (IEnumerable<Namespace>)namespaces);
    downloader = DownloaderFactory.Create(wikiInfo);
    xDocument = this.Download(downloader, (IEnumerable<HttpQueryParameterBase>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(DownloaderTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException15902()
{
    object o;
    WikiInfo wikiInfo;
    Downloader downloader;
    XDocument xDocument;
    o = NamespaceFactory.Create(-2147483633);
    Namespace[] namespaces = new Namespace[1];
    namespaces[0] = (Namespace)o;
    wikiInfo = WikiInfoFactory.Create
                   ("", "@1#\"", (string)null, (IEnumerable<Namespace>)namespaces);
    downloader = DownloaderFactory.Create(wikiInfo);
    xDocument = this.Download(downloader, (IEnumerable<HttpQueryParameterBase>)null);
}
    }
}
