using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq.Expressions;
// <copyright file="ExpressionReplacerTest.Replace.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Expressions.Tests
{
    public partial class ExpressionReplacerTest
    {

[TestMethod]
[PexGeneratedBy(typeof(ExpressionReplacerTest))]
public void Replace789()
{
    object o;
    Expression expression;
    o = ConstantExpressionFactory.Create((object)null);
    expression = this.Replace((Expression)null, (Expression)o, (Expression)null);
    Assert.IsNull((object)expression);
}

[TestMethod]
[PexGeneratedBy(typeof(ExpressionReplacerTest))]
public void Replace564()
{
    Expression expression;
    expression = this.Replace((Expression)null, (Expression)null, (Expression)null);
    Assert.IsNull((object)expression);
}

[TestMethod]
[PexGeneratedBy(typeof(ExpressionReplacerTest))]
public void Replace284()
{
    object o;
    Expression expression;
    o = ConstantExpressionFactory.Create((object)null);
    expression = this.Replace((Expression)o, (Expression)null, (Expression)null);
    Assert.IsNotNull((object)expression);
}
    }
}
