using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="ExpressionParserTest.ReversePropertyName.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Expressions.Tests
{
    public partial class ExpressionParserTest
    {

[TestMethod]
[PexGeneratedBy(typeof(ExpressionParserTest))]
public void ReversePropertyName15()
{
    string s;
    s = this.ReversePropertyName((string)null);
    Assert.AreEqual<string>((string)null, s);
}

[TestMethod]
[PexGeneratedBy(typeof(ExpressionParserTest))]
public void ReversePropertyName697()
{
    string s;
    s = this.ReversePropertyName("defaultvalue");
    Assert.AreEqual<string>("default", s);
}

[TestMethod]
[PexGeneratedBy(typeof(ExpressionParserTest))]
public void ReversePropertyName524()
{
    string s;
    s = this.ReversePropertyName("value");
    Assert.AreEqual<string>("*", s);
}
    }
}
