using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using LinqToWiki;
using LinqToWiki.Internals;
// <copyright file="NamespaceInfoTest.ItemGet.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Internals.Tests
{
    public partial class NamespaceInfoTest
    {

[TestMethod]
[PexGeneratedBy(typeof(NamespaceInfoTest))]
[ExpectedException(typeof(KeyNotFoundException))]
public void ItemGetThrowsKeyNotFoundException978()
{
    NamespaceInfo namespaceInfo;
    Namespace @namespace;
    Namespace[] namespaces = new Namespace[0];
    namespaceInfo = NamespaceInfoFactory.Create((IEnumerable<Namespace>)namespaces);
    @namespace = this.ItemGet(namespaceInfo, 0);
}

[TestMethod]
[PexGeneratedBy(typeof(NamespaceInfoTest))]
public void ItemGet34001()
{
    object o;
    NamespaceInfo namespaceInfo;
    Namespace @namespace;
    o = NamespaceFactory.Create(0);
    Namespace[] namespaces = new Namespace[1];
    namespaces[0] = (Namespace)o;
    namespaceInfo = NamespaceInfoFactory.Create((IEnumerable<Namespace>)namespaces);
    @namespace = this.ItemGet(namespaceInfo, 0);
    Assert.IsNotNull((object)@namespace);
    Assert.AreEqual<int>(0, @namespace.Id);
    Assert.AreEqual<string>("", @namespace.Name);
    Assert.IsNotNull((object)namespaceInfo);
}

[TestMethod]
[PexGeneratedBy(typeof(NamespaceInfoTest))]
[ExpectedException(typeof(KeyNotFoundException))]
public void ItemGetThrowsKeyNotFoundException97801()
{
    object o;
    NamespaceInfo namespaceInfo;
    Namespace @namespace;
    o = NamespaceFactory.Create(855639105);
    Namespace[] namespaces = new Namespace[1];
    namespaces[0] = (Namespace)o;
    namespaceInfo = NamespaceInfoFactory.Create((IEnumerable<Namespace>)namespaces);
    @namespace = this.ItemGet(namespaceInfo, 0);
}

[TestMethod]
[PexGeneratedBy(typeof(NamespaceInfoTest))]
[ExpectedException(typeof(KeyNotFoundException))]
public void ItemGetThrowsKeyNotFoundException97802()
{
    object o;
    NamespaceInfo namespaceInfo;
    Namespace @namespace;
    o = NamespaceFactory.Create(int.MinValue);
    Namespace[] namespaces = new Namespace[1];
    namespaces[0] = (Namespace)o;
    namespaceInfo = NamespaceInfoFactory.Create((IEnumerable<Namespace>)namespaces);
    @namespace = this.ItemGet(namespaceInfo, 0);
}
    }
}
