using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq.Expressions;
using LinqToWiki.Internals;
using LinqToWiki.Parameters;
// <copyright file="PageExpressionParserTest.ParseSelect.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Expressions.Tests
{
    public partial class PageExpressionParserTest
    {

[TestMethod]
[PexGeneratedBy(typeof(PageExpressionParserTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ParseSelectThrowsArgumentNullException216()
{
    PageQueryParameters pageQueryParameters;
    Func<PageData, int> func = (Func<PageData, int>)null;
    pageQueryParameters = this.ParseSelect<int, int>
                              ((Expression<Func<int, int>>)null, (PageQueryParameters)null, out func);
}
    }
}
