using LinqToWiki;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using System.Xml.Linq;
using LinqToWiki.Internals;
// <copyright file="PageDataTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Internals.Tests
{
    public partial class PageDataTest
    {

[TestMethod]
[PexGeneratedBy(typeof(PageDataTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException537()
{
    PageData pageData;
    pageData = this.Constructor((WikiInfo)null, (XElement)null, 
                                (Dictionary<string, QueryTypeProperties>)null, (PagingManager)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PageDataTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException12()
{
    WikiInfo wikiInfo;
    PageData pageData;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("\0", (string)null, (string)null, (IEnumerable<Namespace>)namespaces);
    pageData = this.Constructor(wikiInfo, (XElement)null, 
                                (Dictionary<string, QueryTypeProperties>)null, (PagingManager)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PageDataTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException456()
{
    WikiInfo wikiInfo;
    PageData pageData;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("", (string)null, "", (IEnumerable<Namespace>)namespaces);
    pageData = this.Constructor(wikiInfo, (XElement)null, 
                                (Dictionary<string, QueryTypeProperties>)null, (PagingManager)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PageDataTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException80101()
{
    WikiInfo wikiInfo;
    PageData pageData;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "†??\0", (string)null, (IEnumerable<Namespace>)namespaces);
    pageData = this.Constructor(wikiInfo, (XElement)null, 
                                (Dictionary<string, QueryTypeProperties>)null, (PagingManager)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PageDataTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException80102()
{
    WikiInfo wikiInfo;
    PageData pageData;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "Ā##\0", (string)null, (IEnumerable<Namespace>)namespaces);
    pageData = this.Constructor(wikiInfo, (XElement)null, 
                                (Dictionary<string, QueryTypeProperties>)null, (PagingManager)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PageDataTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException80103()
{
    WikiInfo wikiInfo;
    PageData pageData;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "†##!", (string)null, (IEnumerable<Namespace>)namespaces);
    pageData = this.Constructor(wikiInfo, (XElement)null, 
                                (Dictionary<string, QueryTypeProperties>)null, (PagingManager)null);
}
    }
}
