using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using LinqToWiki.Internals;
// <copyright file="PagePropertiesTPageTest.PropertiesGet.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Internals.Tests
{
    public partial class PagePropertiesTPageTest
    {

[TestMethod]
[PexGeneratedBy(typeof(PagePropertiesTPageTest))]
public void PropertiesGet936()
{
    Dictionary<string, QueryTypeProperties> dictionary;
    dictionary = this.PropertiesGet<int>();
    Assert.IsNotNull((object)dictionary);
    Assert.IsNotNull(dictionary.Comparer);
    Assert.AreEqual<int>(0, dictionary.Count);
}
    }
}
