using Microsoft.ExtendedReflection.DataAccess;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using LinqToWiki.Parameters;
using LinqToWiki;
using LinqToWiki.Download;
using System.Collections.Generic;
using LinqToWiki.Internals;
// <copyright file="PagingManagerTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Internals.Tests
{
    public partial class PagingManagerTest
    {

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException439()
{
    PagingManager pagingManager;
    pagingManager = this.Constructor
                        ((WikiInfo)null, (string)null, (IEnumerable<PropQueryParameters>)null, 
                         (IEnumerable<HttpQueryParameterBase>)null, 
                         (Dictionary<string, QueryTypeProperties>)null, 
                         (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException927()
{
    WikiInfo wikiInfo;
    PagingManager pagingManager;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("\0", (string)null, (string)null, (IEnumerable<Namespace>)namespaces);
    pagingManager = this.Constructor
                        (wikiInfo, (string)null, (IEnumerable<PropQueryParameters>)null, 
                         (IEnumerable<HttpQueryParameterBase>)null, 
                         (Dictionary<string, QueryTypeProperties>)null, 
                         (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException529()
{
    WikiInfo wikiInfo;
    PagingManager pagingManager;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("", (string)null, "", (IEnumerable<Namespace>)namespaces);
    pagingManager = this.Constructor
                        (wikiInfo, (string)null, (IEnumerable<PropQueryParameters>)null, 
                         (IEnumerable<HttpQueryParameterBase>)null, 
                         (Dictionary<string, QueryTypeProperties>)null, 
                         (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException86401()
{
    WikiInfo wikiInfo;
    PagingManager pagingManager;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", " #�\0", (string)null, (IEnumerable<Namespace>)namespaces);
    pagingManager = this.Constructor
                        (wikiInfo, (string)null, (IEnumerable<PropQueryParameters>)null, 
                         (IEnumerable<HttpQueryParameterBase>)null, 
                         (Dictionary<string, QueryTypeProperties>)null, 
                         (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException86402()
{
    WikiInfo wikiInfo;
    PagingManager pagingManager;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", " #타\0", (string)null, (IEnumerable<Namespace>)namespaces);
    pagingManager = this.Constructor
                        (wikiInfo, (string)null, (IEnumerable<PropQueryParameters>)null, 
                         (IEnumerable<HttpQueryParameterBase>)null, 
                         (Dictionary<string, QueryTypeProperties>)null, 
                         (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException86404()
{
    WikiInfo wikiInfo;
    PagingManager pagingManager;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", " #�\0", (string)null, (IEnumerable<Namespace>)namespaces);
    pagingManager = this.Constructor
                        (wikiInfo, (string)null, (IEnumerable<PropQueryParameters>)null, 
                         (IEnumerable<HttpQueryParameterBase>)null, 
                         (Dictionary<string, QueryTypeProperties>)null, 
                         (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException572()
{
    WikiInfo wikiInfo;
    PagingManager pagingManager;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", (string)null, (string)null, (IEnumerable<Namespace>)namespaces);
    PropQueryParameters[] propQueryParameterss = new PropQueryParameters[0];
    pagingManager = this.Constructor(wikiInfo, 
                                     (string)null, (IEnumerable<PropQueryParameters>)propQueryParameterss, 
                                     (IEnumerable<HttpQueryParameterBase>)null, 
                                     (Dictionary<string, QueryTypeProperties>)null, 
                                     (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException57201()
{
    WikiInfo wikiInfo;
    PagingManager pagingManager;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", " ##\0", (string)null, (IEnumerable<Namespace>)namespaces);
    PropQueryParameters[] propQueryParameterss = new PropQueryParameters[0];
    pagingManager = this.Constructor(wikiInfo, 
                                     (string)null, (IEnumerable<PropQueryParameters>)propQueryParameterss, 
                                     (IEnumerable<HttpQueryParameterBase>)null, 
                                     (Dictionary<string, QueryTypeProperties>)null, 
                                     (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException590()
{
    WikiInfo wikiInfo;
    PagingManager pagingManager;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", " #\0\0", (string)null, (IEnumerable<Namespace>)namespaces);
    PropQueryParameters[] propQueryParameterss = new PropQueryParameters[0];
    HttpQueryParameterBase[] httpQueryParameterBases = new HttpQueryParameterBase[0]
      ;
    pagingManager = this.Constructor(wikiInfo, 
                                     (string)null, (IEnumerable<PropQueryParameters>)propQueryParameterss, 
                                     (IEnumerable<HttpQueryParameterBase>)httpQueryParameterBases, 
                                     (Dictionary<string, QueryTypeProperties>)null, 
                                     (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException38603()
{
    WikiInfo wikiInfo;
    PagingManager pagingManager;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "†##", (string)null, (IEnumerable<Namespace>)namespaces);
    pagingManager = this.Constructor
                        (wikiInfo, (string)null, (IEnumerable<PropQueryParameters>)null, 
                         (IEnumerable<HttpQueryParameterBase>)null, 
                         (Dictionary<string, QueryTypeProperties>)null, 
                         (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
public void Constructor973()
{
    WikiInfo wikiInfo;
    Dictionary<string, QueryTypeProperties> dictionary;
    PagingManager pagingManager;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", " #\0", (string)null, (IEnumerable<Namespace>)namespaces);
    dictionary = new Dictionary<string, QueryTypeProperties>(0);
    dictionary["Ā"] = (QueryTypeProperties)null;
    PropQueryParameters[] propQueryParameterss = new PropQueryParameters[0];
    HttpQueryParameterBase[] httpQueryParameterBases = new HttpQueryParameterBase[0]
      ;
    pagingManager = this.Constructor(wikiInfo, 
                                     (string)null, (IEnumerable<PropQueryParameters>)propQueryParameterss, 
                                     (IEnumerable<HttpQueryParameterBase>)httpQueryParameterBases, dictionary, 
                                     (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
    Assert.IsNotNull((object)pagingManager);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException38604()
{
    WikiInfo wikiInfo;
    PagingManager pagingManager;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "%@0x", (string)null, (IEnumerable<Namespace>)namespaces);
    pagingManager = this.Constructor
                        (wikiInfo, (string)null, (IEnumerable<PropQueryParameters>)null, 
                         (IEnumerable<HttpQueryParameterBase>)null, 
                         (Dictionary<string, QueryTypeProperties>)null, 
                         (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException38605()
{
    WikiInfo wikiInfo;
    PagingManager pagingManager;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "%@0/", (string)null, (IEnumerable<Namespace>)namespaces);
    pagingManager = this.Constructor
                        (wikiInfo, (string)null, (IEnumerable<PropQueryParameters>)null, 
                         (IEnumerable<HttpQueryParameterBase>)null, 
                         (Dictionary<string, QueryTypeProperties>)null, 
                         (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException38606()
{
    WikiInfo wikiInfo;
    PagingManager pagingManager;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "%@0X", (string)null, (IEnumerable<Namespace>)namespaces);
    pagingManager = this.Constructor
                        (wikiInfo, (string)null, (IEnumerable<PropQueryParameters>)null, 
                         (IEnumerable<HttpQueryParameterBase>)null, 
                         (Dictionary<string, QueryTypeProperties>)null, 
                         (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException38607()
{
    WikiInfo wikiInfo;
    PagingManager pagingManager;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "%@11", (string)null, (IEnumerable<Namespace>)namespaces);
    pagingManager = this.Constructor
                        (wikiInfo, (string)null, (IEnumerable<PropQueryParameters>)null, 
                         (IEnumerable<HttpQueryParameterBase>)null, 
                         (Dictionary<string, QueryTypeProperties>)null, 
                         (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException45701()
{
    object o;
    WikiInfo wikiInfo;
    PagingManager pagingManager;
    o = NamespaceFactory.Create(0);
    Namespace[] namespaces = new Namespace[1];
    namespaces[0] = (Namespace)o;
    wikiInfo = WikiInfoFactory.Create
                   ("", (string)null, (string)null, (IEnumerable<Namespace>)namespaces);
    pagingManager = this.Constructor
                        (wikiInfo, (string)null, (IEnumerable<PropQueryParameters>)null, 
                         (IEnumerable<HttpQueryParameterBase>)null, 
                         (Dictionary<string, QueryTypeProperties>)null, 
                         (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(PagingManagerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException339()
{
    object o;
    WikiInfo wikiInfo;
    PagingManager pagingManager;
    o = NamespaceFactory.Create(1140990530);
    Namespace[] namespaces = new Namespace[1];
    namespaces[0] = (Namespace)o;
    wikiInfo = WikiInfoFactory.Create
                   ("J", (string)null, (string)null, (IEnumerable<Namespace>)namespaces);
    PropQueryParameters[] propQueryParameterss = new PropQueryParameters[1];
    pagingManager = this.Constructor
                        (wikiInfo, "J", (IEnumerable<PropQueryParameters>)propQueryParameterss, 
                         (IEnumerable<HttpQueryParameterBase>)null, 
                         (Dictionary<string, QueryTypeProperties>)null, 
                         (HttpQueryParameter)null, (Dictionary<string, HttpQueryParameter>)null);
}
    }
}
