using System.Collections.Generic;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using LinqToWiki.Download;
using System.Xml.Linq;
// <copyright file="QueryProcessorTest.GetQueryContinue.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Internals.Tests
{
    public partial class QueryProcessorTest
    {

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
public void GetQueryContinue88801()
{
    object o;
    XElement xElement;
    HttpQueryParameter httpQueryParameter;
    o = XNameFactory.Create("伡", "伡");
    xElement = XElementFactory.Create((XName)o, (XObject)null);
    httpQueryParameter = this.GetQueryContinue(xElement, "伡");
    Assert.IsNull((object)httpQueryParameter);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void GetQueryContinueThrowsArgumentNullException450()
{
    HttpQueryParameter httpQueryParameter;
    httpQueryParameter = this.GetQueryContinue((XElement)null, (string)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void GetQueryContinueThrowsArgumentNullException662()
{
    object o;
    XElement xElement;
    HttpQueryParameter httpQueryParameter;
    o = XNameFactory.Create("스", "쫨");
    xElement = XElementFactory.Create((XName)o, (XObject)null);
    httpQueryParameter = this.GetQueryContinue(xElement, (string)null);
}
    }
}
