using System.Reflection;
using LinqToWiki.Internals;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using LinqToWiki;
// <copyright file="QueryRepresentationTest.ToQueryString.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Internals.Tests
{
    public partial class QueryRepresentationTest
    {

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ToQueryStringThrowsArgumentNullException870()
{
    string s;
    s = this.ToQueryString((Namespace)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
public void ToQueryString789()
{
    object o;
    string s;
    o = NamespaceFactory.Create(0);
    s = this.ToQueryString((Namespace)o);
    Assert.AreEqual<string>("0", s);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
public void ToQueryString589()
{
    object o;
    string s;
    o = NamespaceFactory.Create(-2147483645);
    s = this.ToQueryString((Namespace)o);
    Assert.AreEqual<string>("-2147483645", s);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
public void ToQueryString777()
{
    object o;
    string s;
    o = NamespaceFactory.Create(203);
    s = this.ToQueryString((Namespace)o);
    Assert.AreEqual<string>("203", s);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
public void ToQueryString922()
{
    object o;
    string s;
    o = NamespaceFactory.Create(int.MaxValue);
    s = this.ToQueryString((Namespace)o);
    Assert.AreEqual<string>("2147483647", s);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
public void ToQueryString895()
{
    string s;
    s = this.ToQueryString((string)null);
    Assert.AreEqual<string>((string)null, s);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
public void ToQueryString944()
{
    string s;
    s = this.ToQueryString(default(DateTime));
    Assert.AreEqual<string>("0001-01-01T00:00:00.0000000Z", s);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
public void ToQueryString276()
{
    string s;
    s = this.ToQueryString(false);
    Assert.AreEqual<string>((string)null, s);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
public void ToQueryString710()
{
    string s;
    s = this.ToQueryString(PexSafeHelpers.ByteToBoolean((byte)2));
    Assert.AreEqual<string>("", s);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
public void ToQueryString286()
{
    string s;
    s = this.ToQueryString(int.MinValue);
    Assert.AreEqual<string>("-2147483648", s);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
public void ToQueryString706()
{
    string s;
    s = this.ToQueryString(0);
    Assert.AreEqual<string>("0", s);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
public void ToQueryString23()
{
    string s;
    s = this.ToQueryString(1);
    Assert.AreEqual<string>("1", s);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
public void ToQueryString734()
{
    string s;
    s = this.ToQueryString(49);
    Assert.AreEqual<string>("49", s);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
public void ToQueryString504()
{
    string s;
    s = this.ToQueryString(int.MaxValue);
    Assert.AreEqual<string>("2147483647", s);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
public void ToQueryString318()
{
    string s;
    s = this.ToQueryString(0L);
    Assert.AreEqual<string>("0", s);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ToQueryStringThrowsArgumentNullException877()
{
    string s;
    s = this.ToQueryString((StringValue)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
[ExpectedException(typeof(TargetInvocationException))]
public void ToQueryStringThrowsTargetInvocationException491()
{
    string s;
    s = this.ToQueryString((object)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryRepresentationTest))]
[ExpectedException(typeof(TargetInvocationException))]
public void ToQueryStringThrowsTargetInvocationException782()
{
    string s;
    object s0 = new object();
    s = this.ToQueryString(s0);
}
    }
}
