using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using LinqToWiki.Internals;
// <copyright file="QueryPageProcessorTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Internals.Tests
{
    public partial class QueryPageProcessorTest
    {

[TestMethod]
[PexGeneratedBy(typeof(QueryPageProcessorTest))]
public void Constructor406()
{
    QueryPageProcessor queryPageProcessor;
    queryPageProcessor = this.Constructor((WikiInfo)null);
    Assert.IsNotNull((object)queryPageProcessor);
}
    }
}
