using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using LinqToWiki.Download;
using System.Collections.Generic;
using LinqToWiki;
using System.Xml.Linq;
using LinqToWiki.Internals;
// <copyright file="QueryProcessorTest.Download.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Internals.Tests
{
    public partial class QueryProcessorTest
    {

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException378()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("\0", (string)null, (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException132()
{
    XElement xElement;
    xElement = this.Download((WikiInfo)null, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException5()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("", (string)null, "", (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException354()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "xn--", (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException35401()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", " ??", (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException35402()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "†??", (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException501()
{
    object o;
    WikiInfo wikiInfo;
    XElement xElement;
    o = NamespaceFactory.Create(0);
    Namespace[] namespaces = new Namespace[1];
    namespaces[0] = (Namespace)o;
    wikiInfo = WikiInfoFactory.Create
                   ("", (string)null, (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException35403()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "x?{", (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException45()
{
    object o;
    WikiInfo wikiInfo;
    XElement xElement;
    o = NamespaceFactory.Create(16);
    Namespace[] namespaces = new Namespace[1];
    namespaces[0] = (Namespace)o;
    wikiInfo = WikiInfoFactory.Create
                   ("", (string)null, (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException70304()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", " ?", (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException70305()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "…?#ġ", (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException70306()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "…?#�", (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException70307()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "xn--", "x.:\0", (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException517()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ȁ", "%a@0", (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException70308()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "%0@1", (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException70309()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "xn--", "\0|\0", (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException70310()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo =
      WikiInfoFactory.Create("Ā", "xn--", "\\", (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, 
                             (IEnumerable<HttpQueryParameterBase>)null, (HttpQueryParameter)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException25102()
{
    object o;
    WikiInfo wikiInfo;
    XElement xElement;
    o = NamespaceFactory.Create(int.MinValue);
    Namespace[] namespaces = new Namespace[1];
    namespaces[0] = (Namespace)o;
    wikiInfo = WikiInfoFactory.Create
                   ("", (string)null, (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, (IEnumerable<HttpQueryParameterBase>)null, 
                                       (IEnumerable<HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException250()
{
    XElement xElement;
    xElement =
      this.Download((WikiInfo)null, (IEnumerable<HttpQueryParameterBase>)null, 
                                    (IEnumerable<HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException864()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("\0", (string)null, (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, (IEnumerable<HttpQueryParameterBase>)null, 
                                       (IEnumerable<HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException251()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("", (string)null, "", (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, (IEnumerable<HttpQueryParameterBase>)null, 
                                       (IEnumerable<HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException594()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", " ##\0", (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, (IEnumerable<HttpQueryParameterBase>)null, 
                                       (IEnumerable<HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException59401()
{
    WikiInfo wikiInfo;
    XElement xElement;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "†??", (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, (IEnumerable<HttpQueryParameterBase>)null, 
                                       (IEnumerable<HttpQueryParameter>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void DownloadThrowsArgumentNullException25101()
{
    object o;
    WikiInfo wikiInfo;
    XElement xElement;
    o = NamespaceFactory.Create(0);
    Namespace[] namespaces = new Namespace[1];
    namespaces[0] = (Namespace)o;
    wikiInfo = WikiInfoFactory.Create
                   ("", (string)null, (string)null, (IEnumerable<Namespace>)namespaces);
    xElement = this.Download(wikiInfo, (IEnumerable<HttpQueryParameterBase>)null, 
                                       (IEnumerable<HttpQueryParameter>)null);
}
    }
}
