using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Xml.Linq;
using System.Collections.Generic;
using LinqToWiki;
using LinqToWiki.Internals;
// <copyright file="QueryProcessorTTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Internals.Tests
{
    public partial class QueryProcessorTTest
    {

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException556()
{
    QueryProcessor<int> queryProcessor;
    queryProcessor =
      this.Constructor<int>((WikiInfo)null, (QueryTypeProperties<int>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException125()
{
    WikiInfo wikiInfo;
    QueryProcessor<int> queryProcessor;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("\0", (string)null, (string)null, (IEnumerable<Namespace>)namespaces);
    queryProcessor = this.Constructor<int>(wikiInfo, (QueryTypeProperties<int>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException271()
{
    WikiInfo wikiInfo;
    QueryProcessor<int> queryProcessor;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("", (string)null, "", (IEnumerable<Namespace>)namespaces);
    queryProcessor = this.Constructor<int>(wikiInfo, (QueryTypeProperties<int>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException55101()
{
    WikiInfo wikiInfo;
    QueryProcessor<int> queryProcessor;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "†??", (string)null, (IEnumerable<Namespace>)namespaces);
    queryProcessor = this.Constructor<int>(wikiInfo, (QueryTypeProperties<int>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException784()
{
    object o;
    WikiInfo wikiInfo;
    QueryProcessor<int> queryProcessor;
    o = NamespaceFactory.Create(0);
    Namespace[] namespaces = new Namespace[1];
    namespaces[0] = (Namespace)o;
    wikiInfo = WikiInfoFactory.Create
                   ("", (string)null, (string)null, (IEnumerable<Namespace>)namespaces);
    queryProcessor = this.Constructor<int>(wikiInfo, (QueryTypeProperties<int>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException55103()
{
    WikiInfo wikiInfo;
    QueryProcessor<int> queryProcessor;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "xn--", "\0|\0.", (IEnumerable<Namespace>)namespaces);
    queryProcessor = this.Constructor<int>(wikiInfo, (QueryTypeProperties<int>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException9()
{
    WikiInfo wikiInfo;
    QueryProcessor<int> queryProcessor;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "Ā??\0", (string)null, (IEnumerable<Namespace>)namespaces);
    queryProcessor = this.Constructor<int>(wikiInfo, (QueryTypeProperties<int>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException901()
{
    WikiInfo wikiInfo;
    QueryProcessor<int> queryProcessor;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "†??\0", (string)null, (IEnumerable<Namespace>)namespaces);
    queryProcessor = this.Constructor<int>(wikiInfo, (QueryTypeProperties<int>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException716()
{
    object o;
    WikiInfo wikiInfo;
    QueryProcessor<int> queryProcessor;
    o = NamespaceFactory.Create(1140850688);
    Namespace[] namespaces = new Namespace[1];
    namespaces[0] = (Namespace)o;
    wikiInfo = WikiInfoFactory.Create
                   ("\"", (string)null, (string)null, (IEnumerable<Namespace>)namespaces);
    queryProcessor = this.Constructor<int>(wikiInfo, (QueryTypeProperties<int>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException902()
{
    WikiInfo wikiInfo;
    QueryProcessor<int> queryProcessor;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "xn--", "\0|\0", (IEnumerable<Namespace>)namespaces);
    queryProcessor = this.Constructor<int>(wikiInfo, (QueryTypeProperties<int>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException904()
{
    WikiInfo wikiInfo;
    QueryProcessor<int> queryProcessor;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "%0@1", (string)null, (IEnumerable<Namespace>)namespaces);
    queryProcessor = this.Constructor<int>(wikiInfo, (QueryTypeProperties<int>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException905()
{
    WikiInfo wikiInfo;
    QueryProcessor<int> queryProcessor;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo =
      WikiInfoFactory.Create("Ā", "xn--", "\\", (IEnumerable<Namespace>)namespaces);
    queryProcessor = this.Constructor<int>(wikiInfo, (QueryTypeProperties<int>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException906()
{
    WikiInfo wikiInfo;
    QueryProcessor<int> queryProcessor;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "xn-H", (string)null, (IEnumerable<Namespace>)namespaces);
    queryProcessor = this.Constructor<int>(wikiInfo, (QueryTypeProperties<int>)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException907()
{
    WikiInfo wikiInfo;
    QueryProcessor<int> queryProcessor;
    Namespace[] namespaces = new Namespace[0];
    wikiInfo = WikiInfoFactory.Create
                   ("Ā", "0.:0", (string)null, (IEnumerable<Namespace>)namespaces);
    queryProcessor = this.Constructor<int>(wikiInfo, (QueryTypeProperties<int>)null);
}
    }
}
