using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Xml.Linq;
using LinqToWiki.Download;
using LinqToWiki.Parameters;
using LinqToWiki.Internals;
using System.Collections.Generic;
// <copyright file="QueryProcessorTest.ProcessParameters.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Internals.Tests
{
    public partial class QueryProcessorTest
    {

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void ProcessParametersThrowsNullReferenceException7()
{
    Dictionary<string, string[]> dictionary;
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    dictionary = new Dictionary<string, string[]>(0);
    dictionary[""] = (string[])null;
    Tuple<string, string>[] tuples = new Tuple<string, string>[0];
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)dictionary, 
                               (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, false, false, 0);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessParametersThrowsArgumentNullException13801()
{
    Dictionary<string, string[]> dictionary;
    QueryTypeProperties<int> queryTypeProperties;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    dictionary = new Dictionary<string, string[]>(0);
    dictionary[""] = (string[])null;
    Tuple<string, string>[] tuples = new Tuple<string, string>[0];
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)dictionary, 
                               (Func<XElement, WikiInfo, int>)null);
    iEnumerable = this.ProcessParameters
                      ((QueryTypeProperties)queryTypeProperties, (QueryParameters)null, 
                       false, false, 0);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessParametersThrowsArgumentNullException288()
{
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    iEnumerable = this.ProcessParameters
                      ((QueryTypeProperties)null, (QueryParameters)null, false, false, 0);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessParametersThrowsArgumentNullException138()
{
    QueryTypeProperties<int> queryTypeProperties;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[0];
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    iEnumerable = this.ProcessParameters
                      ((QueryTypeProperties)queryTypeProperties, (QueryParameters)null, 
                       false, false, 0);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
public void ProcessParameters414()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[0];
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, false, false, 0);
    Assert.IsNotNull((object)iEnumerable);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
public void ProcessParameters368()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[0];
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, true, false, 0);
    Assert.IsNotNull((object)iEnumerable);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
public void ProcessParameters13()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[0];
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, true, false, 1);
    Assert.IsNotNull((object)iEnumerable);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
public void ProcessParameters468()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[0];
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, true, false, -1);
    Assert.IsNotNull((object)iEnumerable);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
public void ProcessParameters311()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[0];
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, true, false, int.MinValue);
    Assert.IsNotNull((object)iEnumerable);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
public void ProcessParameters432()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[0];
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, true, false, int.MaxValue);
    Assert.IsNotNull((object)iEnumerable);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
public void ProcessParameters83()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[1];
    Tuple<string, string> s0 = new Tuple<string, string>((string)null, (string)null)
      ;
    tuples[0] = s0;
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, false, false, 0);
    Assert.IsNotNull((object)iEnumerable);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
public void ProcessParameters161()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[1];
    Tuple<string, string> s0 = new Tuple<string, string>((string)null, (string)null)
      ;
    tuples[0] = s0;
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, false, true, 0);
    Assert.IsNotNull((object)iEnumerable);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
public void ProcessParameters41401()
{
    Dictionary<string, string[]> dictionary;
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    string[] ss = new string[0];
    dictionary = new Dictionary<string, string[]>(0);
    dictionary[""] = ss;
    Tuple<string, string>[] tuples = new Tuple<string, string>[0];
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)dictionary, 
                               (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, false, false, 0);
    Assert.IsNotNull((object)iEnumerable);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void ProcessParametersThrowsNullReferenceException215()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[1];
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, false, false, 0);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
public void ProcessParameters36802()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[0];
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, "", new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, true, false, 0);
    Assert.IsNotNull((object)iEnumerable);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(InvalidOperationException))]
public void ProcessParametersThrowsInvalidOperationException851()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[0];
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, false, true, 0);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void ProcessParametersThrowsNullReferenceException282()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[1];
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, false, true, 0);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(InvalidOperationException))]
public void ProcessParametersThrowsInvalidOperationException679()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[1];
    Tuple<string, string> s0 = new Tuple<string, string>("action", (string)null);
    tuples[0] = s0;
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, default(QueryType?), 
                               default(SortType?), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, false, true, 1);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
public void ProcessParameters285()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[1];
    Tuple<string, string> s0 = new Tuple<string, string>((string)null, (string)null)
      ;
    tuples[0] = s0;
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, "", new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, true, true, 0);
    Assert.IsNotNull((object)iEnumerable);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
public void ProcessParameters121()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[2];
    Tuple<string, string> s0 = new Tuple<string, string>((string)null, (string)null)
      ;
    tuples[0] = s0;
    tuples[1] = s0;
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, false, false, 0);
    Assert.IsNotNull((object)iEnumerable);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(InvalidOperationException))]
public void ProcessParametersThrowsInvalidOperationException15()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[2];
    Tuple<string, string> s0 = new Tuple<string, string>((string)null, (string)null)
      ;
    tuples[0] = s0;
    tuples[1] = s0;
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, false, true, 0);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
public void ProcessParameters782()
{
    QueryTypeProperties<int> queryTypeProperties;
    PropQueryParameters propQueryParameters;
    IEnumerable<HttpQueryParameterBase> iEnumerable;
    Tuple<string, string>[] tuples = new Tuple<string, string>[5];
    Tuple<string, string> s0 = new Tuple<string, string>((string)null, (string)null)
      ;
    tuples[0] = s0;
    tuples[1] = s0;
    tuples[2] = s0;
    tuples[3] = s0;
    tuples[4] = s0;
    queryTypeProperties = QueryTypePropertiesFactory.Create
                              ((string)null, (string)null, new QueryType?(QueryType.Prop), 
                               new SortType?(SortType.Newer), (IEnumerable<Tuple<string, string>>)tuples, 
                               (IDictionary<string, string[]>)null, (Func<XElement, WikiInfo, int>)null);
    propQueryParameters = new PropQueryParameters((string)null);
    iEnumerable = this.ProcessParameters((QueryTypeProperties)queryTypeProperties, 
                                         (QueryParameters)propQueryParameters, false, false, 0);
    Assert.IsNotNull((object)iEnumerable);
}
    }
}
