using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Xml.Linq;
using System.Collections.Generic;
using LinqToWiki.Download;
// <copyright file="QueryProcessorTest.GetQueryContinues.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Internals.Tests
{
    public partial class QueryProcessorTest
    {

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void GetQueryContinuesThrowsArgumentNullException67()
{
    Dictionary<string, HttpQueryParameter> dictionary;
    dictionary = this.GetQueryContinues((XElement)null);
}

[TestMethod]
[PexGeneratedBy(typeof(QueryProcessorTest))]
public void GetQueryContinues815()
{
    object o;
    XElement xElement;
    Dictionary<string, HttpQueryParameter> dictionary;
    o = XNameFactory.Create("ɼ쒄", "ɼ쒄");
    xElement = XElementFactory.Create((XName)o, (XObject)null);
    dictionary = this.GetQueryContinues(xElement);
    Assert.IsNotNull((object)dictionary);
    Assert.IsNotNull(dictionary.Comparer);
    Assert.AreEqual<int>(0, dictionary.Count);
}
    }
}
