using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using LinqToWiki.Parameters;
using System.Collections.Generic;
using LinqToWiki.Internals;
// <copyright file="QueryPageProcessorTest.ExecuteList.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Internals.Tests
{
    public partial class QueryPageProcessorTest
    {

[TestMethod]
[PexGeneratedBy(typeof(QueryPageProcessorTest))]
public void ExecuteList545()
{
    QueryPageProcessor queryPageProcessor;
    IEnumerable<int> iEnumerable;
    queryPageProcessor = QueryPageProcessorFactory.Create((WikiInfo)null);
    iEnumerable =
      this.ExecuteList<int>(queryPageProcessor, (PageQueryParameters)null, 
                            (Func<PageData, int>)null, (Dictionary<string, QueryTypeProperties>)null);
    Assert.IsNotNull((object)iEnumerable);
    Assert.IsNotNull((object)queryPageProcessor);
}
    }
}
