using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using LinqToWiki.Collections;
// <copyright file="TupleListT1T2Test.Add.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Collections.Tests
{
    public partial class TupleListT1T2Test
    {

[TestMethod]
[PexGeneratedBy(typeof(TupleListT1T2Test))]
public void Add955()
{
    TupleList<int, int> tupleList;
    Tuple<int, int>[] tuples = new Tuple<int, int>[0];
    tupleList = TupleListFactory.Create((IEnumerable<Tuple<int, int>>)tuples);
    this.Add<int, int>(tupleList, 0, 0);
    Assert.IsNotNull((object)tupleList);
    Assert.AreEqual<int>(4, ((List<Tuple<int, int>>)tupleList).Capacity);
    Assert.AreEqual<int>(1, ((List<Tuple<int, int>>)tupleList).Count);
}

[TestMethod]
[PexGeneratedBy(typeof(TupleListT1T2Test))]
public void Add914()
{
    TupleList<int, int> tupleList;
    Tuple<int, int>[] tuples = new Tuple<int, int>[1];
    tupleList = TupleListFactory.Create((IEnumerable<Tuple<int, int>>)tuples);
    this.Add<int, int>(tupleList, 0, 0);
    Assert.IsNotNull((object)tupleList);
    Assert.AreEqual<int>(2, ((List<Tuple<int, int>>)tupleList).Capacity);
    Assert.AreEqual<int>(2, ((List<Tuple<int, int>>)tupleList).Count);
}
    }
}
