using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq.Expressions;
using LinqToWiki.Expressions;
// <copyright file="UsedPropertiesGathererTest.Visit.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Expressions.Tests
{
    public partial class UsedPropertiesGathererTest
    {

[TestMethod]
[PexGeneratedBy(typeof(UsedPropertiesGathererTest))]
public void Visit94104()
{
    UsedPropertiesGatherer usedPropertiesGatherer;
    object o;
    BinaryExpression binaryExpression;
    Expression expression;
    usedPropertiesGatherer = UsedPropertiesGathererFactory.Create();
    object boxd = (object)(default(double));
    o = ConstantExpressionFactory.Create(boxd);
    binaryExpression = BinaryExpressionFactory.Create
                           (ExpressionType.Power, (Expression)o, (Expression)o);
    expression = this.Visit(usedPropertiesGatherer, (Expression)binaryExpression);
    Assert.IsNotNull((object)expression);
    Assert.IsNotNull((object)usedPropertiesGatherer);
}

[TestMethod]
[PexGeneratedBy(typeof(UsedPropertiesGathererTest))]
public void Visit208()
{
    UsedPropertiesGatherer usedPropertiesGatherer;
    Expression expression;
    usedPropertiesGatherer = UsedPropertiesGathererFactory.Create();
    expression = this.Visit(usedPropertiesGatherer, (Expression)null);
    Assert.IsNull((object)expression);
    Assert.IsNotNull((object)usedPropertiesGatherer);
}

[TestMethod]
[PexGeneratedBy(typeof(UsedPropertiesGathererTest))]
public void Visit568()
{
    UsedPropertiesGatherer usedPropertiesGatherer;
    object o;
    object o1;
    Expression expression;
    usedPropertiesGatherer = UsedPropertiesGathererFactory.Create();
    object boxb = (object)(default(bool));
    o = ConstantExpressionFactory.Create(boxb);
    o1 = UnaryExpressionFactory.Create
             (ExpressionType.IsTrue, (Expression)o, (Type)null);
    expression = this.Visit(usedPropertiesGatherer, (Expression)o1);
    Assert.IsNotNull((object)expression);
    Assert.IsNotNull((object)usedPropertiesGatherer);
}

[TestMethod]
[PexGeneratedBy(typeof(UsedPropertiesGathererTest))]
public void Visit56801()
{
    UsedPropertiesGatherer usedPropertiesGatherer;
    object o;
    object o1;
    Expression expression;
    usedPropertiesGatherer = UsedPropertiesGathererFactory.Create();
    object boxb = (object)(default(bool));
    o = ConstantExpressionFactory.Create(boxb);
    o1 = UnaryExpressionFactory.Create
             (ExpressionType.IsFalse, (Expression)o, (Type)null);
    expression = this.Visit(usedPropertiesGatherer, (Expression)o1);
    Assert.IsNotNull((object)expression);
    Assert.IsNotNull((object)usedPropertiesGatherer);
}

[TestMethod]
[PexGeneratedBy(typeof(UsedPropertiesGathererTest))]
public void Visit941()
{
    UsedPropertiesGatherer usedPropertiesGatherer;
    object o;
    BinaryExpression binaryExpression;
    Expression expression;
    usedPropertiesGatherer = UsedPropertiesGathererFactory.Create();
    object s0 = new object();
    o = ConstantExpressionFactory.Create(s0);
    binaryExpression = BinaryExpressionFactory.Create
                           (ExpressionType.Coalesce, (Expression)o, (Expression)o);
    expression = this.Visit(usedPropertiesGatherer, (Expression)binaryExpression);
    Assert.IsNotNull((object)expression);
    Assert.IsNotNull((object)usedPropertiesGatherer);
}

[TestMethod]
[PexGeneratedBy(typeof(UsedPropertiesGathererTest))]
public void Visit94101()
{
    UsedPropertiesGatherer usedPropertiesGatherer;
    object o;
    BinaryExpression binaryExpression;
    Expression expression;
    usedPropertiesGatherer = UsedPropertiesGathererFactory.Create();
    object s0 = new object();
    o = ConstantExpressionFactory.Create(s0);
    binaryExpression = BinaryExpressionFactory.Create
                           (ExpressionType.Equal, (Expression)o, (Expression)o);
    expression = this.Visit(usedPropertiesGatherer, (Expression)binaryExpression);
    Assert.IsNotNull((object)expression);
    Assert.IsNotNull((object)usedPropertiesGatherer);
}

[TestMethod]
[PexGeneratedBy(typeof(UsedPropertiesGathererTest))]
public void Visit94102()
{
    UsedPropertiesGatherer usedPropertiesGatherer;
    object o;
    BinaryExpression binaryExpression;
    Expression expression;
    usedPropertiesGatherer = UsedPropertiesGathererFactory.Create();
    object boxb = (object)(default(bool));
    o = ConstantExpressionFactory.Create(boxb);
    binaryExpression = BinaryExpressionFactory.Create
                           (ExpressionType.OrElse, (Expression)o, (Expression)o);
    expression = this.Visit(usedPropertiesGatherer, (Expression)binaryExpression);
    Assert.IsNotNull((object)expression);
    Assert.IsNotNull((object)usedPropertiesGatherer);
}

[TestMethod]
[PexGeneratedBy(typeof(UsedPropertiesGathererTest))]
public void Visit94103()
{
    UsedPropertiesGatherer usedPropertiesGatherer;
    object o;
    BinaryExpression binaryExpression;
    Expression expression;
    usedPropertiesGatherer = UsedPropertiesGathererFactory.Create();
    object s0 = new object();
    o = ConstantExpressionFactory.Create(s0);
    binaryExpression = BinaryExpressionFactory.Create
                           (ExpressionType.NotEqual, (Expression)o, (Expression)o);
    expression = this.Visit(usedPropertiesGatherer, (Expression)binaryExpression);
    Assert.IsNotNull((object)expression);
    Assert.IsNotNull((object)usedPropertiesGatherer);
}
    }
}
