using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using LinqToWiki.Expressions;
// <copyright file="UsedPropertiesGathererTest.UsedPropertiesGet.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace LinqToWiki.Expressions.Tests
{
    public partial class UsedPropertiesGathererTest
    {

[TestMethod]
[PexGeneratedBy(typeof(UsedPropertiesGathererTest))]
public void UsedPropertiesGet732()
{
    UsedPropertiesGatherer usedPropertiesGatherer;
    IEnumerable<string> iEnumerable;
    usedPropertiesGatherer = UsedPropertiesGathererFactory.Create();
    iEnumerable = this.UsedPropertiesGet(usedPropertiesGatherer);
    Assert.IsNull((object)iEnumerable);
    Assert.IsNotNull((object)usedPropertiesGatherer);
}
    }
}
