using System.Xml;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace System.Xml.Linq
{
    public partial class FactoryTest
    {

[TestMethod]
[PexGeneratedBy(typeof(FactoryTest))]
[PexRaisedException(typeof(ArgumentNullException))]
public void XNameCreateTestThrowsArgumentNullException199()
{
    this.XNameCreateTest((string)null);
}

[TestMethod]
[PexGeneratedBy(typeof(FactoryTest))]
[PexRaisedException(typeof(ArgumentException))]
public void XNameCreateTestThrowsArgumentException909()
{
    this.XNameCreateTest("");
}

[TestMethod]
[PexGeneratedBy(typeof(FactoryTest))]
[PexRaisedException(typeof(XmlException))]
public void XNameCreateTestThrowsXmlException328()
{
    this.XNameCreateTest("\0");
}

[TestMethod]
[PexGeneratedBy(typeof(FactoryTest))]
[PexRaisedException(typeof(XmlException))]
public void XNameCreateTestThrowsXmlException645()
{
    this.XNameCreateTest("\0");
}
    }
}
